### PR TITLE
Replace version numbers

### PR DESCRIPTION
**Pull request by PalmTreeVI**
Remove references to 5.2.x / 5.3.x / 5.4.x  version numbers and replace with version shortcode - `[version]` - which grabs the current version from github latest.

### CODE REVIEW

**Comment by Liquid369** [comment]
concept ACK
I just want to test to verify the results before we merge? is there a way to do so from this system? 
Will approve afterwards

**Comment by PalmTreeVI** [comment]
Its markdown, similiar to github, changes can be seen on my fork https://github.com/PalmTreeVI/PIVX-Doc-Website-Content?organization=PalmTreeVI&organization=PalmTreeVI or with any markdown pre-viewer like https://markdownlivepreview.com/

**Comment by PalmTreeVI** [comment]
It's tested on my local test server.

[Screenshot_2022-12-26_14-28-29](https://user-images.githubusercontent.com/64500998/209578512-398c111b-9ef8-430f-9091-66b9820507e0.png)

**Review by DeanSparrow — APPROVED** [review]
Approved

**Review by Liquid369 — COMMENTED** [review]
tACK 13edc60d7206ad7323fb4e7b3c62a68c831f18d2
After checking in the live markdown viewer it looks fine to me.

**Pull request merged**
